### ISSUE TITLE
Empty preview with the default Flutter page

### ISSUE THREAD

**Issue by g123k** [andrasferenczi/idea_widget_preview#2] opened 2022-11-16 23:02 UTC
Hi,

If I use a single Widget (like a Text, a FloatingActionButton…), the preview works well.
However, with a page like `MyApp()` in the default template (and the same goes for `MyHomePage`), it won't work:

<img width="1435" alt="Screenshot 2022-11-17 at 00 02 19" src="https://user-images.githubusercontent.com/246838/202313338-b48f5c5f-398e-4a33-945a-314503fb98c8.png">

```dart
class ExamplePreview extends PreviewProvider {
  @override
  List<Preview> get previews => [
        // 3) Individual declarations
        Preview(
          title: "Simple",
          builder: (BuildContext context) {
            return MyApp();
          },
        )
      ];
}

```

**Comment by andrasferenczi** [comment] 2022-11-17 06:16
Sry this happens. Can you answer the following questions:
- Does that still occur after refreshing the preview?
- Is there any errors visible in the `Widget Preview Logs` tab? There should be a tab in the bottom that shows the log of the processes. Can you see anything there?

I'll try to reproduce it later, but in case you can do a minimum reproducible example of the widget, that would be really helpful.

**Comment by g123k** [comment] 2022-11-17 20:14
> Sry this happens. Can you answer the following questions:
> 
> * Does that still occur after refreshing the preview?

Yes, and even after restarting the IDE

> * Is there any errors visible in the `Widget Preview Logs` tab? There should be a tab in the bottom that shows the log of the processes. Can you see anything there?

No error is displayed, everything seems to be normal.
There's only the blank previex.

> 
> I'll try to reproduce it later, but in case you can do a minimum reproducible example of the widget, that would be really helpful.

This is just the Hello World from Flutter

**Comment by andrasferenczi** [comment] 2022-11-17 20:51
So this is caused by the preview package not being able to calculate the height of individual widgets. (I have to investigate further what could be done with empty result, I'll probably go for some default value.)

In case you have an widget with unbounded height, you can preview it by specifying a device:

```dart
class StartAppPreview extends PreviewProvider {
  @override
  List<Preview> get previews => [
        Preview(
          title: "Simple",
          device: Device(
            info: Devices.ios.iPad,
          ),
          builder: (BuildContext context) {
            return StartApp();
          },
        )
      ];
}
```

This results in something like this (zoomed out):

<img width="618" alt="Screenshot 2022-11-17 at 21 47 44" src="https://user-images.githubusercontent.com/17592224/202556509-20ff21fc-44f0-4007-b662-844b48e641b0.png">

I won't close this issue yet, as this is a local fix. It would be ideal to have a sensible default or some message.

**Comment by andrasferenczi** [comment] 2022-12-18 20:31
Closing this, as `v2022.1.4` has an error message in these cases.

**Closed as completed by andrasferenczi** 2022-12-18 20:31 UTC
Labels: Bug, Dart Package
